[project]
name = "npg-python-lib"
description = "A library of Python functions and classes common to NPG applications."
license = "GPL-3.0-or-later AND BSD-3-Clause"
license-files = ["LICENSE", "src/npg/_vendor/sqlalchemy_utils/LICENSE"]
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Keith James", email = "kdj@sanger.ac.uk" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Programming Language :: Python"
]
keywords = ["npg"]
requires-python = ">=3.11"

dynamic = ["version"]

dependencies = [
    "python-dateutil >=2.9.0,<3",
    "structlog >=25",
]

[project.optional-dependencies]
db = ["SQLAlchemy >=2,<3"]
test = [
    "black >=26,<27",
    "pytest >=9,<10",
    "pytest-it >=0.1.5",
    "SQLAlchemy >=2,<3"
]

[project.urls]
homepage = "https://github.com/wtsi-npg/npg-python-lib"
repository = "https://github.com/wtsi-npg/npg-python-lib.git"

[build-system]
requires = ["setuptools>=80", "wheel", "setuptools-git-versioning>=3,<4"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Note: we are relying on setuptools' automatic package discovery, so no further
# configuration is required. This is possible because npg-irods-python uses a standard
# src layout. See the following for more information:
#
# https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout

[tool.setuptools.package-data]
"npg._vendor.sqlalchemy_utils" = ["LICENSE", "README.md"]

[tool.setuptools-git-versioning]
enabled = true

[tool.black]
# Preserve upstream formatting to simplify reviewing vendored updates.
extend-exclude = "/src/npg/_vendor/"
